CardManagement/CardManagement-war/src/java/cardmanagement/entity/Card.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cardmanagement.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author julius
 */
@Entity
@Table(name = "card")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Card.findAll", query = "SELECT c FROM Card c"),
    @NamedQuery(name = "Card.findByCardId", query = "SELECT c FROM Card c WHERE c.cardId = :cardId"),
    @NamedQuery(name = "Card.findByCardNumber", query = "SELECT c FROM Card c WHERE c.cardNumber = :cardNumber"),
    @NamedQuery(name = "Card.findByStatus", query = "SELECT c FROM Card c WHERE c.status = :status"),
    @NamedQuery(name = "Card.findByCreatedDate", query = "SELECT c FROM Card c WHERE c.createdDate = :createdDate"),
    @NamedQuery(name = "Card.findByActivatedDate", query = "SELECT c FROM Card c WHERE c.activatedDate = :activatedDate"),
    @NamedQuery(name = "Card.findByPrimarySecondaryFlag", query = "SELECT c FROM Card c WHERE c.primarySecondaryFlag = :primarySecondaryFlag"),
    @NamedQuery(name = "Card.findByExpiryDate", query = "SELECT c FROM Card c WHERE c.expiryDate = :expiryDate"),
    @NamedQuery(name = "Card.findByAvailableBalance", query = "SELECT c FROM Card c WHERE c.availableBalance = :availableBalance")})
public class Card implements Serializable {

   
    
    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = true)
    //@NotNull
    @Size(min = 1, max = 255)
    @Column(name = "card_id")
    private String cardId;
    
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "card_number")
    private String cardNumber;
    
    
//    @Enumerated(EnumType.STRING)
//    private CardStatusEnum status;
    
    @Basic(optional = true)
    @Column(name = "status")
    private String status;
    @Size(min = 1, max = 255)

 
    //@NotNull
    @Column(name = "created_date")
    @Temporal(TemporalType.DATE)
    private Date createdDate;
    @Basic(optional = true)
    
    @NotNull
    @Column(name = "activated_date")
    @Temporal(TemporalType.DATE)
    private Date activatedDate;
    @Basic(optional = false)
    
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "primary_secondary_flag")
    private String primarySecondaryFlag;
    @Basic(optional = false)
    
    @NotNull
    @Column(name = "expiry_date")
    @Temporal(TemporalType.DATE)
    private Date expiryDate;
    @Basic(optional = false)
    
    @NotNull
    @Size(min = 1, max = 255)
    @Column(name = "available_balance")
    private String availableBalance;
    

    public Card() {
    }

    public Card(String cardId) {
        this.cardId = cardId;
    }

    public Card(String cardId, String cardNumber, String status, Date createdDate, Date activatedDate, String primarySecondaryFlag, Date expiryDate, String availableBalance) {
        this.cardId = cardId;
        this.cardNumber = cardNumber;
        this.status = status;
        this.createdDate = createdDate;
        this.activatedDate = activatedDate;
        this.primarySecondaryFlag = primarySecondaryFlag;
        this.expiryDate = expiryDate;
        this.availableBalance = availableBalance;
    }

    public String getCardId() {
        return cardId;
    }

    public void setCardId(String cardId) {
        this.cardId = cardId;
    }

    public String getCardNumber() {
        return cardNumber;
    }

    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public Date getCreatedDate() {
        return createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public Date getActivatedDate() {
        return activatedDate;
    }

    public void setActivatedDate(Date activatedDate) {
        this.activatedDate = activatedDate;
    }

    public String getPrimarySecondaryFlag() {
        return primarySecondaryFlag;
    }

    public void setPrimarySecondaryFlag(String primarySecondaryFlag) {
        this.primarySecondaryFlag = primarySecondaryFlag;
    }

    public Date getExpiryDate() {
        return expiryDate;
    }

    public void setExpiryDate(Date expiryDate) {
        this.expiryDate = expiryDate;
    }

    public String getAvailableBalance() {
        return availableBalance;
    }

    public void setAvailableBalance(String availableBalance) {
        this.availableBalance = availableBalance;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (cardId != null ? cardId.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Card)) {
            return false;
        }
        Card other = (Card) object;
        if ((this.cardId == null && other.cardId != null) || (this.cardId != null && !this.cardId.equals(other.cardId))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "cardmanagement.entity.Card[ cardId=" + cardId + " ]";
    }
    
}

CardManagement/CardManagement-war/src/java/controller/CardController.java
package controller;

import cardmanagement.entity.Card;
import controller.util.JsfUtil;
import controller.util.PaginationHelper;
import cardmanagement.ejb.CardFacade;

import java.io.Serializable;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("cardController")
@SessionScoped
public class CardController implements Serializable {
    
    
    
    private HashMap<String,Object> cardType= new HashMap<String,Object>(){{
       put("PRIMARY","PRIMARY");
       put("SECONDARY","SECONDARY");
    }};

    public HashMap<String, Object> getCardType() {
        return cardType;
    }

    public void setCardType(HashMap<String, Object> cardType) {
        this.cardType = cardType;
    }

    
    

    private Card current;
    private DataModel items = null;
    @EJB
    private cardmanagement.ejb.CardFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public CardController() {
    }

    public Card getSelected() {
        if (current == null) {
            current = new Card();
            selectedItemIndex = -1;
        }
        return current;
    }
    
    
    

    private CardFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Card) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Card();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("CardCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Card) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("CardUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Card) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("CardDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public Card getCard(java.lang.String id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = Card.class)
    public static class CardControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            CardController controller = (CardController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "cardController");
            return controller.getCard(getKey(value));
        }

        java.lang.String getKey(String value) {
            java.lang.String key;
            key = value;
            return key;
        }

        String getStringKey(java.lang.String value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Card) {
                Card o = (Card) object;
                return getStringKey(o.getCardId());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Card.class.getName());
            }
        }

    }

}

CardManagement/CardManagement-war/web/card/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateCardTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                 
                    <h:outputLabel value="#{bundle.CreateCardLabel_cardNumber}" for="cardNumber" />
                    <h:inputText id="cardNumber" value="#{cardController.selected.cardNumber}" title="#{bundle.CreateCardTitle_cardNumber}" required="true" requiredMessage="#{bundle.CreateCardRequiredMessage_cardNumber}"/>
                  
                    <h:outputLabel value="#{bundle.CreateCardLabel_activatedDate}" for="activatedDate" />
                    <h:inputText id="activatedDate" value="#{cardController.selected.activatedDate}" title="#{bundle.CreateCardTitle_activatedDate}" required="true" requiredMessage="#{bundle.CreateCardRequiredMessage_activatedDate}">
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.CreateCardLabel_expiryDate}" for="expiryDate" />
                    <h:inputText id="expiryDate" value="#{cardController.selected.expiryDate}" title="#{bundle.CreateCardTitle_expiryDate}" required="true" requiredMessage="#{bundle.CreateCardRequiredMessage_expiryDate}">
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.CreateCardLabel_availableBalance}" for="availableBalance" />
                    <h:inputText id="availableBalance" value="#{cardController.selected.availableBalance}" title="#{bundle.CreateCardTitle_availableBalance}" required="true" requiredMessage="#{bundle.CreateCardRequiredMessage_availableBalance}"/>
                    
                    <h:outputLabel value="Card Type" for="primarySecondaryFlag" />
                    <h:selectOneMenu value="#{cardController.selected.primarySecondaryFlag}" required="true" requiredMessage="Card Type must be selected">
   			<f:selectItems value="#{cardController.cardType}" />
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{cardController.create}" value="#{bundle.CreateCardSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{cardController.prepareList}" value="#{bundle.CreateCardShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateCardIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

CardManagement/CardManagement-war/web/card/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditCardTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditCardLabel_cardId}" for="cardId" />
                    <h:inputText id="cardId" value="#{cardController.selected.cardId}" title="#{bundle.EditCardTitle_cardId}" required="true" requiredMessage="#{bundle.EditCardRequiredMessage_cardId}"/>
                    <h:outputLabel value="#{bundle.EditCardLabel_cardNumber}" for="cardNumber" />
                    <h:inputText id="cardNumber" value="#{cardController.selected.cardNumber}" title="#{bundle.EditCardTitle_cardNumber}" required="true" requiredMessage="#{bundle.EditCardRequiredMessage_cardNumber}"/>
                    <h:outputLabel value="#{bundle.EditCardLabel_status}" for="status" />
                    <h:inputText id="status" value="#{cardController.selected.status}" title="#{bundle.EditCardTitle_status}" required="true" requiredMessage="#{bundle.EditCardRequiredMessage_status}"/>
                    <h:outputLabel value="#{bundle.EditCardLabel_createdDate}" for="createdDate" />
                    <h:inputText id="createdDate" value="#{cardController.selected.createdDate}" title="#{bundle.EditCardTitle_createdDate}" required="true" requiredMessage="#{bundle.EditCardRequiredMessage_createdDate}">
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditCardLabel_activatedDate}" for="activatedDate" />
                    <h:inputText id="activatedDate" value="#{cardController.selected.activatedDate}" title="#{bundle.EditCardTitle_activatedDate}" required="true" requiredMessage="#{bundle.EditCardRequiredMessage_activatedDate}">
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditCardLabel_primarySecondaryFlag}" for="primarySecondaryFlag" />
                    <h:inputText id="primarySecondaryFlag" value="#{cardController.selected.primarySecondaryFlag}" title="#{bundle.EditCardTitle_primarySecondaryFlag}" required="true" requiredMessage="#{bundle.EditCardRequiredMessage_primarySecondaryFlag}"/>
                    <h:outputLabel value="#{bundle.EditCardLabel_expiryDate}" for="expiryDate" />
                    <h:inputText id="expiryDate" value="#{cardController.selected.expiryDate}" title="#{bundle.EditCardTitle_expiryDate}" required="true" requiredMessage="#{bundle.EditCardRequiredMessage_expiryDate}">
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:inputText>
                    <h:outputLabel value="#{bundle.EditCardLabel_availableBalance}" for="availableBalance" />
                    <h:inputText id="availableBalance" value="#{cardController.selected.availableBalance}" title="#{bundle.EditCardTitle_availableBalance}" required="true" requiredMessage="#{bundle.EditCardRequiredMessage_availableBalance}"/>
                </h:panelGrid>
                <h:commandLink action="#{cardController.update}" value="#{bundle.EditCardSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditCardViewLink}"/>
                <br />
                <h:commandLink action="#{cardController.prepareList}" value="#{bundle.EditCardShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditCardIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

CardManagement/CardManagement-war/web/card/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListCardTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListCardEmpty}" rendered="#{cardController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{cardController.items.rowCount > 0}">
                    <h:outputText value="#{cardController.pagination.pageFirstItem + 1}..#{cardController.pagination.pageLastItem + 1}/#{cardController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{cardController.previous}" value="#{bundle.Previous} #{cardController.pagination.pageSize}" rendered="#{cardController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{cardController.next}" value="#{bundle.Next} #{cardController.pagination.pageSize}" rendered="#{cardController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{cardController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCardTitle_cardId}"/>
                            </f:facet>
                            <h:outputText value="#{item.cardId}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCardTitle_cardNumber}"/>
                            </f:facet>
                            <h:outputText value="#{item.cardNumber}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCardTitle_status}"/>
                            </f:facet>
                            <h:outputText value="#{item.status}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCardTitle_createdDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.createdDate}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCardTitle_activatedDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.activatedDate}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCardTitle_primarySecondaryFlag}"/>
                            </f:facet>
                            <h:outputText value="#{item.primarySecondaryFlag}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCardTitle_expiryDate}"/>
                            </f:facet>
                            <h:outputText value="#{item.expiryDate}">
                                <f:convertDateTime pattern="MM/dd/yyyy" />
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListCardTitle_availableBalance}"/>
                            </f:facet>
                            <h:outputText value="#{item.availableBalance}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{cardController.prepareView}" value="#{bundle.ListCardViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{cardController.prepareEdit}" value="#{bundle.ListCardEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{cardController.destroy}" value="#{bundle.ListCardDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{cardController.prepareCreate}" value="#{bundle.ListCardCreateLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListCardIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

CardManagement/CardManagement-war/web/card/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewCardTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewCardLabel_cardId}"/>
                    <h:outputText value="#{cardController.selected.cardId}" title="#{bundle.ViewCardTitle_cardId}"/>
                    <h:outputText value="#{bundle.ViewCardLabel_cardNumber}"/>
                    <h:outputText value="#{cardController.selected.cardNumber}" title="#{bundle.ViewCardTitle_cardNumber}"/>
                    <h:outputText value="#{bundle.ViewCardLabel_status}"/>
                    <h:outputText value="#{cardController.selected.status}" title="#{bundle.ViewCardTitle_status}"/>
                    <h:outputText value="#{bundle.ViewCardLabel_createdDate}"/>
                    <h:outputText value="#{cardController.selected.createdDate}" title="#{bundle.ViewCardTitle_createdDate}">
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:outputText>
                    <h:outputText value="#{bundle.ViewCardLabel_activatedDate}"/>
                    <h:outputText value="#{cardController.selected.activatedDate}" title="#{bundle.ViewCardTitle_activatedDate}">
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:outputText>
                    <h:outputText value="#{bundle.ViewCardLabel_primarySecondaryFlag}"/>
                    <h:outputText value="#{cardController.selected.primarySecondaryFlag}" title="#{bundle.ViewCardTitle_primarySecondaryFlag}"/>
                    <h:outputText value="#{bundle.ViewCardLabel_expiryDate}"/>
                    <h:outputText value="#{cardController.selected.expiryDate}" title="#{bundle.ViewCardTitle_expiryDate}">
                        <f:convertDateTime pattern="MM/dd/yyyy" />
                    </h:outputText>
                    <h:outputText value="#{bundle.ViewCardLabel_availableBalance}"/>
                    <h:outputText value="#{cardController.selected.availableBalance}" title="#{bundle.ViewCardTitle_availableBalance}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{cardController.destroyAndView}" value="#{bundle.ViewCardDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewCardEditLink}"/>
                <br />
                <h:commandLink action="#{cardController.prepareCreate}" value="#{bundle.ViewCardCreateLink}" />
                <br />
                <h:commandLink action="#{cardController.prepareList}" value="#{bundle.ViewCardShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewCardIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>